// import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
// import { Toaster, toast } from 'sonner';
import "./globals.css";
export { metadata } from '@/app/_components/metadata'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "影子跟读 | Shadow Reading",
//   description: "Generated by create next app",
//   icons: {
//     icon: [
//       { url: "/logo2.png", type: "image/png", sizes: "64x64" }
//     ]
//   }
// };

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported but less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        {children}

      </body>
    </html>
  );
}
