// import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./_components/nav";
import LeftSlide from "./_components/leftSlide";
import "../globals.css";
import { isMobileServer } from "@/lib/isMobile";
import MobilTab from "./_components/MobilTab";
// import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
    title: "影子跟读 | Shadow Reading",
    description: "Generated by create next app",
    icons: {
        icon: [{ url: "/logo2.png", type: "image/png", sizes: "64x64" }],
    },
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    // Also supported but less commonly used
    // interactiveWidget: 'resizes-visual',
};

export default async function RootLayout({ children }) {
    // const isMobile = await isMobileServer()

    return (
        <>
            <div className="bg-[#fafafa] page-wrap">
                <Nav />
                <div>
                    <div className="flex">
                        <LeftSlide />
                        <div className="w-full border-t border-l border-border flex-1 p-2.5 overflow-y-auto bg-white relative right-silde-wrap">
                            {children}
                        </div>
                    </div>

                    <MobilTab />
                </div>
            </div>
        </>
    );
}
